import 'package:islamy/data/model/reciter_model.dart';

class AppLists{
  static List<String> searchedSurasNamesListEng = [];
  static List<String> searchedSurasNamesListAr  = [];
  static List<int>   searchedSurasIndexList= [];
  static List<int> searchedSurasVersesNumList= [];


  static List<String> egyptGovernorates = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Port Said",
    "Suez",
    "Damietta",
    "Dakahlia",
    "Sharqia",
    "Qalyubia",
    "Kafr El Sheikh",
    "Gharbia",
    "Menoufia",
    "Beheira",
    "Ismailia",
    "Beni Suef",
    "Faiyum",
    "Minya",
    "Asyut",
    "Sohag",
    "Qena",
    "Luxor",
    "Aswan",
    "Red Sea",
    "New Valley",
    "Matrouh",
    "North Sinai",
    "South Sinai"
  ];

  static const List<String> surasNamesListAr = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس",
  ];

  static const List<String> surasNamesListEng = [
    "Al-Fatiha",
    "Al-Baqarah",
    "Aal-E-Imran",
    "An-Nisa",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Tawbah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "Ta-Ha",
    "Al-Anbiya",
    "Al-Hajj",
    "Al-Mu’minun",
    "An-Nur",
    "Al-Furqan",
    "Ash-Shu’ara",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajda",
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "Ya-Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Ash-Shura",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jathiyah",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Adh-Dhariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi’ah",
    "Al-Hadid",
    "Al-Mujadila",
    "Al-Hashr",
    "Al-Mumtahina",
    "As-Saff",
    "Al-Jumu’ah",
    "Al-Munafiqun",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haaqqa",
    "Al-Ma’arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddaththir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat",
    "An-Naba",
    "An-Nazi’at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Inshiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A’la",
    "Al-Ghashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Lail",
    "Ad-Duha",
    "Ash-Sharh",
    "At-Tin",
    "Al-‘Alaq",
    "Al-Qadr",
    "Al-Bayyina",
    "Az-Zalzalah",
    "Al-Adiyat",
    "Al-Qari’ah",
    "At-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Ma’un",
    "Al-Kawthar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas",
  ];

  static const List<int> versesNumList = [
    7,
    286,
    200,
    176,
    120,
    165,
    206,
    75,
    129,
    109,
    123,
    111,
    43,
    52,
    99,
    128,
    111,
    110,
    98,
    135,
    112,
    78,
    118,
    64,
    77,
    227,
    93,
    88,
    69,
    60,
    34,
    30,
    73,
    54,
    45,
    83,
    182,
    88,
    75,
    85,
    54,
    53,
    89,
    59,
    37,
    35,
    38,
    29,
    18,
    45,
    60,
    49,
    62,
    55,
    78,
    96,
    29,
    22,
    24,
    13,
    14,
    11,
    11,
    18,
    12,
    12,
    30,
    52,
    52,
    44,
    28,
    28,
    20,
    56,
    40,
    31,
    50,
    40,
    46,
    42,
    29,
    19,
    36,
    25,
    22,
    17,
    19,
    26,
    30,
    20,
    15,
    21,
    11,
    8,
    5,
    19,
    5,
    8,
    8,
    11,
    11,
    8,
    3,
    9,
    5,
    4,
    6,
    3,
    6,
    3,
    5,
    4,
    5,
    6
  ];

  static List<ReciterModel> reciters = [
    ReciterModel(url: "AbdulSamad_64kbps_QuranExplorer.Com", title: "AbdulSamad mujawwad"),
    ReciterModel(url: "Abdul_Basit_Murattal_192kbps.Com", title: "AbdulSamad murattal"),
    ReciterModel(url: "Abu_Bakr_Ash-Shaatree_128kbps", title: "Abu Bakr Ash-Shaatree"),
    ReciterModel(url: "Ahmed_Neana_128kbps", title: "Ahmed Neana"),
    ReciterModel(url: "Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net", title: "Ahmed Ibn Ali Al-Ajamy"),
    ReciterModel(url: "Alafasy_128kbps", title: "Alafasy"),
    ReciterModel(url: "Ali_Jaber_64kbps", title: "Ali Jaber"),
    ReciterModel(url: "Ghamadi_40kbps", title: "Ghamadi"),
    ReciterModel(url: "Fares_Abbad_64kbps", title: "Fares Abbad"),
    ReciterModel(url: "Hudhaify_128kbps", title: "Hudhaify"),
    ReciterModel(url: "Husary_128kbps", title: "Al Husary"),
    ReciterModel(url: "Husary_128kbps_Mujawwad", title: "Al Husary - Mujawwad"),
    ReciterModel(url: "MaherAlMuaiqly128kbps", title: "Maher AlMuaiqly"),
    ReciterModel(url: "Minshawy_Mujawwad_192kbps", title: "Al Minshawy - Mujawwad"),
    ReciterModel(url: "Minshawy_Murattal_128kbps", title: "Al Minshawy - Murattal"),
    ReciterModel(url: "Mohammad_al_Tablaway_128kbps", title: "Mohammad Al Tablaway"),
    ReciterModel(url: "Muhammad_Ayyoub_128kbps", title: "Muhammad Ayyoub"),
    ReciterModel(url: "Muhammad_Jibreel_128kbps", title: "Muhammad Jibreel"),
    ReciterModel(url: "Mustafa_Ismail_48kbps", title: "Mustafa Ismail"),
    ReciterModel(url: "Nasser_Alqatami_128kbps", title: "Nasser Alqatami"),
    ReciterModel(url: "Saood_ash-Shuraym_128kbps", title: "Saood Ash-Shuraym (128kbps)"),
    ReciterModel(url: "Saood_ash-Shuraym_64kbps", title: "Saood Ash-Shuraym (64kbps)"),
    ReciterModel(url: "Yasser_Ad-Dussary_128kbps", title: "Yasser Ad-Dussary"),
    ReciterModel(url: "mahmoud_ali_al_banna_32kbps", title: "Mahmoud Ali Al Banna"),
  ];


}